proc-memory: include missing pattern definitions
```
D:\a\NdGameSdk\NdGameSdk\shared\Utility\memory/proc-memory.hpp(25,9): error : unknown type name 'Pattern' [D:\a\NdGameSdk\NdGameSdk\build\Utility.vcxproj
```